# Site settings
title: Swamp Castle
email: dave@edx.org
description: > 
  

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://swampcastle.org"
twitter_username: ormsbee
github_username:  ormsbee

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["tables", "no_intra_emphasis", "autolink"]

# Conversion
excerpt_separator: "\n\n\n"